Bot_token = 'NzgwNDA4MTE2NTEyMjkyODg0.X7upsg.7oV_H2hNnZ_NDoQ-udPBsPpEF0I' #BOT TOKEN BURAYA
Prefıx = '!!' #PREFİX BURAYA
BOT_ID = '780408116512292884'
# BOT_ID = ''

Owner = '303922834982305793' #GEREKLİ. YÜKLE, YENİLE , KALDIR , STATUS GİBİ KOMUTLARIN ERİŞİMİNİ YALNIZCA OWNER'A AÇAR!


#MEME VE ADULT/NSFW KOMUTLARININ ÇALIŞMASI İÇİN REDDİT DEVELOPER YERİNDEN APP OLUŞTURUP GEREKLİ ID VE SECRET BİLGİLERİNİ AŞAĞIDA Kİ YERE YAZIN

MEME_CHANNEL_ID = '791740048273440768'
ADULT_NSFW_CHANNEL_ID = '791745865983197187'
# ADULT_NSFW_CHANNEL_ID = 'BURAYA ADULT/NSFW KOMUTLARININ KULLANILACAĞI KANAL ID SİNİ YAZIN'  #GEREKLİ!
# MEME_CHANNEL_ID = 'BURAYA MEME KOMUTLARININ KULLANILACAĞI KANAL ID SİNİ YAZIN' 

REDDIT_APP_ID='E4eejxpJtjoeKw'   #REDDİT APP İD BURAYA 
REDDIT_APP_SECRET='XWrw8BNA1mjdUZ1yOn9YZ07GDxgz4g' # REDDİT APP SECRET BURAYA
REDDIT_ENABLED_MEME_SUBREDDITS = [
     'burdurland',
     'KGBTR',
     'Memes_Of_The_Dank',     #SUBREDDİT BAŞLIKLARI İLE O BAŞLIKLARDAN GÖNDERİ ÇEKER. ÇOĞALTABİLİRSİNİZ
     'bruhmoment'
]
REDDIT_ADULT = [
    'porn',
    'nsfw',
    'pusy',                   #SUBREDDİT BAŞLIKLARI İLE O BAŞLIKLARDAN GÖNDERİ ÇEKER. ÇOĞALTABİLİRSİNİZ
    'hot girls',
    'pornhub',
    'thatsthespot'
]
REDDIT_ADULT_GIF = [  
    'pussy gif',
    'blowjob gif',
    'porn gif',                 #SUBREDDİT BAŞLIKLARI İLE O BAŞLIKLARDAN GÖNDERİ ÇEKER. ÇOĞALTABİLİRSİNİZ
    'NSFW_GIF',
    'thatsthespot'
]
